-- 0.0.2

CREATE TABLE [core].[users] (
	id UNIQUEIDENTIFIER NOT NULL,
	email NVARCHAR(256) NOT NULL,
	passwordHash NVARCHAR(MAX) NOT NULL,

	PRIMARY KEY(id)
);

ALTER TABLE [core].[users] ADD
	CONSTRAINT [DEF_users_id]  DEFAULT (NEWSEQUENTIALID()) FOR [id],
	CONSTRAINT [UN_users_email] UNIQUE (email)